<?php
HTML_Render_Head($js_vars);
echo $CSS_Main;
echo $JS_JQuery;
echo $CSS_JQX;
echo $JS_JQX;
echo $JS_GetTheme;
?>
<script type="text/javascript">

$(document).ready(function(){
	$("#msg").hide();
});
</script>
<?php HTML_Render_Body_Start(); 
genHeading('AddNewSource',true);
$attributes = array('class' => 'form-horizontal', 'name' => 'addsource');
echo form_open('source/addsource', $attributes);
genInput('Organization','Organization', 'Organization', true);
echo '<span class="em">' .getTxt('ExTitle1').'</span>';
genInput('Description','SourceDescription','SourceDescription', true);
echo '<span class="em">' .getTxt('ExDescript').'</span>';
genInput('Link','SourceLink','SourceLink', true);
echo '<span class="em">' .getTxt('ExMetaLink').'</span>';
genInput('ContactName','ContactName','ContactName', true);
echo '<span class="em">' .getTxt('ExName').'</span>';
genInput('Phone','Phone','Phone', true);
echo '<span class="em">' .getTxt('ExPhone').'</span>';
genInput('Email','Email','Email', true);
echo '<span class="em">' .getTxt('ExEmail').'</span>';
genInput('Address','Address','Address', true);
genInput('City','City','City', true);
genSelect('State','State','State',$stateOptions,'SelectEllipsis',true);
genInput('Zip','ZipCode','ZipCode', true);
genInput('Citation','Citation','Citation', true);
echo '<span class="em">' .getTxt('ExCitation').'</span>';
genInput('MetadataIDSemicolon','MetadataID','MetadataID', true);
echo '<span class="em">' .getTxt('MetadataAutoGenerated').'</span>';
genSelect('TopicCategory','TopicCategory','TopicCategory',$topicOptions,'SelectEllipsis', true);
genInput('Title','Title','Title', true);
echo '<span class="em">' .getTxt('ExTitle2').'</span>';
genInput('Abstract','Abstract','Abstract', true);
echo '<span class="em">' .getTxt('ExAbstract1').'</span>';
genInput('MetaLink','MetadataLink','MetadataLink', true);
echo '<span class="em">' .getTxt('Optional').'</span>';
?>
<div class="col-md-5 col-md-offset-5">
       <input type="SUBMIT" name="submit" value="<?php echo getTxt('AddSourceButton');?>" class="button"/>
       <input type="reset" name="Reset" value="<?php echo getTxt('Cancel'); ?>" class="button" style="width: auto" />
</div>
</div>
<?php HTML_Render_Body_End(); ?>
<script>
$("#resetButton").click(function() {
	$("form")[0].reset();
	 $("html, body").animate({ scrollTop: 0 }, "slow");
  return false;
});

$("#addsource").submit(function(){

	//Validate all fields
	if(($("#Organization").val())==""){
		//alert("Please enter an organization for the source.");
		alert(<?php echo "'".$EnterOrganization."'"; ?>);
		return false;
	}

	if(($("#SourceDescription").val())==""){
		//alert("Please enter a description for the source.");
		alert(<?php echo "'".$EnterDescription."'"; ?>);
		return false;
	}

	if(($("#SourceLink").val())!=""){
		var regexp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
		if(!($("#SourceLink").val().match(regexp))){
			alert("Invalid url for sourcelink");
			alert(<?php echo "'".$InvalidSourceLinkURL."'"; ?>);
			return false;
		}
	}

	if(($("#ContactName").val())==""){
		//alert("Please enter a contact name for the source.");
		alert(<?php echo "'".$EnterContactName."'"; ?>);
		return false;
	}

	if(($("#Phone").val())==""){
		//alert("Please enter a phone number for the contact person.");
		alert(<?php echo "'".$EnterPhoneNumber."'"; ?>);
		return false;
	}

	//Phone Validation
	var regex = /^([+]*([0-9]{1})*[- .(]*([0-9]{3})*[- .)]*[0-9]{3}[- .]*[0-9]{4})+$/;
	if(!($("#Phone").val().match(regex))){
		//alert("Invalid phone number");
		alert(<?php echo "'".$InvalidPhoneNumber."'"; ?>);
		return false;
	}

	if(($("#Email").val())==""){
		//alert("Please enter an email address for the source.");
		alert(<?php echo "'".$EnterEmailAddress."'"; ?>);
		return false;
	}
	//Email validation
	var pattern= /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;

	if(!($("#Email").val().match(pattern))){
		alert(<?php echo "'".$InvalidEmailAddress."'"; ?>);
		return false;
	}

	if(($("#Address").val())==""){
		alert(<?php echo "'".$EnterAddress."'"; ?>);
		return false;
	}
	
	if(($("#City").val())==""){
		alert(<?php echo "'".$EnterCity."'"; ?>);
		return false;
	}

	if(($("#state option:selected").val())==-1){
		alert(<?php echo "'".$SelectSourceState."'"; ?>);
		return false;
	}

	if(($("#ZipCode").val())==""){
		alert(<?php echo "'".$EnterZipCode."'"; ?>);
		return false;
	}

	if(!($("#ZipCode").val().match(/^\d{5}(-\d{4})?$/))){
		alert(<?php echo "'".$InvalidZipCode."'"; ?>);
		return false;
	}

	//Validate MetadataID info
	if(($("#TopicCategory option:selected").val())==-1){
		alert(<?php echo "'".$SelectTopicCategory."'"; ?>);
		return false;
	}

	if(($("#Title").val())==""){
		alert(<?php echo "'".$EnterMetadataTitle."'"; ?>);
		return false;
	}

	if(($("#Abstract").val())==""){
		alert(<?php echo "'".$EnterMetadataAbstract."'"; ?>);
		return false;
	}

	if(($("#MetadataLink").val())!=""){
		var regexp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
			if(!($("#ContactName").val().match(regexp))){
				alert(<?php echo "'".$InvalidURLMetadata."'"; ?>);
				return false;
			}
	}
		
	});
return false;
});
</script>

